/*
 * USBRemoteControllerBinaryDevice.h
 *
 *  Created on: May 29, 2020
 *      Author: epffpe
 */

#ifndef DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBREMOTECONTROLLERBINARYDEVICE_H_
#define DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBREMOTECONTROLLERBINARYDEVICE_H_

#define USBRCBINDEVICE_ID                      6

#define USBREMOTECONTROLLERBINARYDEVICE_TASK_STACK_SIZE        2048
#define USBREMOTECONTROLLERBINARYDEVICE_TASK_PRIORITY          5

#define USBREMOTECONTROLLERBINARYDEVICE_CLOCK_TIMEOUT       10
#define USBREMOTECONTROLLERBINARYDEVICE_CLOCK_PERIOD        1000

#define USBREMOTECONTROLLERBINARYWORKER_TASK_STACK_SIZE        1024
#define USBREMOTECONTROLLERBINARYWORKER_TASK_PRIORITY          6

#ifdef __cplusplus
extern "C"  {
#endif


#ifdef  __DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBREMOTECONTROLLERBINARYDEVICE_GLOBAL
    #define __DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBREMOTECONTROLLERBINARYDEVICE_EXT
#else
    #define __DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBREMOTECONTROLLERBINARYDEVICE_EXT  extern
#endif


__DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBREMOTECONTROLLERBINARYDEVICE_EXT
void vUSBRCBinaryDevice_Params_init(Device_Params *params, uint32_t address);

__DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBREMOTECONTROLLERBINARYDEVICE_EXT
int xUSBRCBinaryCMD_checksum(int *datos, unsigned int N);
__DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBREMOTECONTROLLERBINARYDEVICE_EXT
int xUSBRCBinaryCMD_frameCreate(char * buffer, int kind, char *data, int len);


#ifdef __cplusplus
}
#endif





#endif /* DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBREMOTECONTROLLERBINARYDEVICE_H_ */
