/*
 * TCPBinaryCMD_Rosen.h
 *
 *  Created on: Apr 9, 2020
 *      Author: epffpe
 */

#ifndef DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_H_
#define DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_H_

typedef enum
{
    CHARACTERISTIC_TCPRCBIN_ROSEN_DIRECT_COMMAND1_ID = 0x01,
    CHARACTERISTIC_TCPRCBIN_ROSEN_DIRECT_COMMAND2_ID,
    CHARACTERISTIC_TCPRCBIN_ROSEN_STEVE_COMMAND_POWER_SET_ID,
    CHARACTERISTIC_TCPRCBIN_ROSEN_STEVE_COMMAND_POWER_GET_ID,
    CHARACTERISTIC_TCPRCBIN_ROSEN_STEVE_COMMAND_SOURCE_SET_ID,
    CHARACTERISTIC_TCPRCBIN_ROSEN_STEVE_COMMAND_SOURCE_GET_ID,
    CHARACTERISTIC_TCPRCBIN_ROSEN_STEVE_COMMAND_DVD_CONTROL_SET_ID,
    CHARACTERISTIC_TCPRCBIN_ROSEN_STEVE_COMMAND_DVD_CONTROL_GET_ID,
    CHARACTERISTIC_TCPRCBIN_ROSEN_STEVE_COMMAND_DVD_LOADED_GET_ID,
    CHARACTERISTIC_TCPRCBIN_ROSEN_STEVE_COMMAND_DVD_PLAYING_GET_ID,
    CHARACTERISTIC_TCPRCBIN_ROSEN_STEVE_COMMAND_SM_SOURCE_SET_ID,
    CHARACTERISTIC_TCPRCBIN_ROSEN_STEVE_COMMAND_SM_SOURCE_GET_ID,
} TCP_CMD_ROSEN_service_characteristics_t;

typedef struct {
    uint32_t deviceID;
    uint8_t  data[];
}TCP_CMD_ROSEN_genericCommand_payload_t;


#ifdef __cplusplus
extern "C"
{
#endif

#ifdef  __DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_GLOBAL
    #define __DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
#else
    #define __DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT    extern
#endif

__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void vTCPRCBin_ROSENService_ValueChangeHandler(char_data_t *pCharData);



__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENGenericDirectCommand1(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENGenericDirectCommand2(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENPowerSetCommand(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENPowerGetCommand(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENSourceSetCommand(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENSourceGetCommand(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENDVDControlSetCommand(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENDVDPowerGetCommand(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENDVDLoadedGetCommand(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENDVDPlayingGetCommand(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENUDPSMSourceSetCommand(int clientfd, char *payload, int32_t size);
__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_EXT
void TCPBin_ROSENUDPSMSourceGetCommand(int clientfd, char *payload, int32_t size);


//*****************************************************************************
//
// Mark the end of the C bindings section for C++ compilers.
//
//*****************************************************************************
#ifdef __cplusplus
}
#endif





#endif /* DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_ROSEN_TCPBINARYCMD_ROSEN_H_ */
