/*
 * TCPBinaryCMD_FlashFileSystem.h
 *
 *  Created on: Dec 17, 2019
 *      Author: epenate
 */

#ifndef DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_FLASHFILESYSTEM_TCPBINARYCMD_FLASHFILESYSTEM_H_
#define DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_FLASHFILESYSTEM_TCPBINARYCMD_FLASHFILESYSTEM_H_




#ifdef  __DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_FLASHFILESYSTEM_TCPBINARYCMD_FLASHFILESYSTEM_GLOBAL
    #define __DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_FLASHFILESYSTEM_TCPBINARYCMD_FLASHFILESYSTEM_EXT
#else
    #define __DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_FLASHFILESYSTEM_TCPBINARYCMD_FLASHFILESYSTEM_EXT  extern
#endif


#ifdef __cplusplus
extern "C" {
#endif

__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_FLASHFILESYSTEM_TCPBINARYCMD_FLASHFILESYSTEM_EXT
void vTCPRCBin_FlashFileSystem_getInternalFlashStatus(int clientfd, char *payload, int32_t size);

__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_FLASHFILESYSTEM_TCPBINARYCMD_FLASHFILESYSTEM_EXT
void vTCPRCBin_FlashFileSystem_formatInternalFlashStatus(int clientfd, char *payload, int32_t size);

__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_FLASHFILESYSTEM_TCPBINARYCMD_FLASHFILESYSTEM_EXT
void vTCPRCBin_FlashFileSystem_getExternalFlashStatus(int clientfd, char *payload, int32_t size);

__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_FLASHFILESYSTEM_TCPBINARYCMD_FLASHFILESYSTEM_EXT
void vTCPRCBin_FlashFileSystem_formatExternalFlashStatus(int clientfd, char *payload, int32_t size);


#ifdef __cplusplus
}
#endif




#endif /* DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_FLASHFILESYSTEM_TCPBINARYCMD_FLASHFILESYSTEM_H_ */
