/*
 * AVDSRS485Device.h
 *
 *  Created on: Apr 22, 2020
 *      Author: epffpe
 */

#ifndef DEVICES_AVDS_AVDSRS485DEVICE_H_
#define DEVICES_AVDS_AVDSRS485DEVICE_H_



#define DEVICES_AVDS_AVDSRS485DEVICE_TASK_STACK_SIZE        2048
#define DEVICES_AVDS_AVDSRS485DEVICE_TASK_PRIORITY          2

#define DEVICES_AVDS_AVDSRS485DEVICE_CLOCK_TIMEOUT        1000
#define DEVICES_AVDS_AVDSRS485DEVICE_CLOCK_PERIOD         1000


typedef enum
{
    SERVICE_AVDSRS485DEVICE_ALTO_EMULATOR_UUID = 0x0201,
    SERVICE_AVDSRS485DEVICE_STEVE_COMMANDS_UUID,
} AVDS485Device_service_UUID_t;


typedef enum
{
    CHARACTERISTIC_SERVICE_AVDSRS485DEVICE_STEVE_COMMAND_SERIAL_CHANNEL_SET_ID = 0x01,
    CHARACTERISTIC_SERVICE_AVDSRS485DEVICE_STEVE_COMMAND_SERIAL_CHANNEL_GET_ID,
} AVDS485Device_service_Steve_Command_characteristics_t;




#ifdef  __DEVICES_AVDS_AVDSRS485DEVICE_GLOBAL
    #define __DEVICES_AVDS_AVDSRS485DEVICE_EXT
#else
    #define __DEVICES_AVDS_AVDSRS485DEVICE_EXT  extern
#endif


#ifdef __cplusplus
extern "C"  {
#endif



__DEVICES_AVDS_AVDSRS485DEVICE_EXT
void vAVDS485Device_Params_init(Device_Params *params, uint32_t address);


#ifdef __cplusplus
}
#endif




#endif /* DEVICES_AVDS_AVDSRS485DEVICE_H_ */
