/*
 * TCPBinaryCMD_DAC.h
 *
 *  Created on: Jul 23, 2019
 *      Author: epenate
 */

#ifndef DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_DAC_TCPBINARYCMD_DAC_H_
#define DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_DAC_TCPBINARYCMD_DAC_H_




#ifdef  __DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_DAC_TCPBINARYCMD_DAC_GLOBAL
    #define __DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_DAC_TCPBINARYCMD_DAC_EXT
#else
    #define __DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_DAC_TCPBINARYCMD_DAC_EXT  extern
#endif


#ifdef __cplusplus
extern "C" {
#endif

__DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_DAC_TCPBINARYCMD_DAC_EXT
void vTCPRCBin_DAC_setVoltageValue(int clientfd, char *payload, int32_t size);

#ifdef __cplusplus
}
#endif







#endif /* DEVICES_REMOTECONTROLLER_TCPBINARYCOMMANDS_DAC_TCPBINARYCMD_DAC_H_ */
