/*
 * USBBinaryCMD_System.h
 *
 *  Created on: Oct 19, 2020
 *      Author: epenate
 */

#ifndef DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBBINARYCOMMANDS_SYSTEM_USBBINARYCMD_SYSTEM_H_
#define DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBBINARYCOMMANDS_SYSTEM_USBBINARYCMD_SYSTEM_H_



#ifdef __cplusplus
extern "C" {
#endif

#ifdef  __DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBBINARYCOMMANDS_SYSTEM_USBBINARYCMD_SYSTEM_GLOBAL
    #define __DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBBINARYCOMMANDS_SYSTEM_USBBINARYCMD_SYSTEM_EXT
#else
    #define __DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBBINARYCOMMANDS_SYSTEM_USBBINARYCMD_SYSTEM_EXT  extern
#endif

__DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBBINARYCOMMANDS_SYSTEM_USBBINARYCMD_SYSTEM_EXT
void vUSBBinaryCMD_Reboot(char *payload, int32_t size);


#ifdef __cplusplus
}
#endif




#endif /* DEVICES_USBSERIAL_USBREMOTECONTROLLER_USBBINARYCOMMANDS_SYSTEM_USBBINARYCMD_SYSTEM_H_ */
